Add function to print text in colour

diff --git a/dot_functions b/dot_functions
--- a/dot_functions
+++ b/dot_functions
@@ -25,7 +25,7 @@ function git-track {
 }
 
 # ==============================================================================
-# scripting
+# Common functions
 
 # Check if variable is set to true
 #
@@ -41,3 +41,45 @@ function is-arg-true() {
   fi
 }
 export -f is-arg-true > /dev/null
+
+# Print header
+#
+# Usage:
+#   print-header "This is a header"
+
+function print-header() {
+    printf -- "\n%s${*}%s\n\n" >&2 "$BOLD$BLUE" "$RESET"
+}
+
+# Print error
+#
+# Usage:
+#   print-error "This is an error"
+
+function print-error() {
+    printf -- "%sError: ${*}%s\n" >&2 "$RED" "$RESET"
+}
+
+# ==============================================================================
+# Helper functions
+
+function _setup_color() {
+
+  # Only use colors if connected to a terminal
+  if [ -t 1 ]; then
+    RED=$(printf '\033[31m')
+    GREEN=$(printf '\033[32m')
+    YELLOW=$(printf '\033[33m')
+    BLUE=$(printf '\033[34m')
+    BOLD=$(printf '\033[1m')
+    RESET=$(printf '\033[m')
+  else
+    RED=""
+    GREEN=""
+    YELLOW=""
+    BLUE=""
+    BOLD=""
+    RESET=""
+  fi
+}
+_setup_color
